### PR TITLE
Build with AppVeyor CI

### PR DESCRIPTION
**Pull request by jhasse**
This adds a configuration file for AppVeyor which will automatically build ticpp in 32 bit / 64 bit and debug / release.

The only thing needed is to activate it on AppVeyor, output will look similar to this: https://ci.appveyor.com/project/jhasse/ticpp

### CODE REVIEW

**Comment by rjpcomputing** [comment]
How do I activate it on AppVeyor?

**Comment by jhasse** [comment]
Login with your GitHub account and activate `rjpcomputing/ticpp` @ PROJECTS -> NEW PROJECT.

**Comment by rjpcomputing** [comment]
Done

**Comment by jhasse** [comment]
Awesome :) https://ci.appveyor.com/project/rjpcomputing/ticpp

I'm also working on building wxFormBuilder btw (WIP): https://ci.appveyor.com/project/jhasse/wxformbuilder

**Pull request merged**
